export const categories=[
    {
        id: 1,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-29-600x600.jpg',
        name : '6 Speed Gearbox',
        price : 644,
        rate: 4.25 ,
        precise : 0.5,
    },
    {
        id: 2,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-4-600x600.jpg',
        name : '600-Series Floor Mount 3-Pedal Assembly',
        price : 457,
        rate: 4.5 ,
        precise : 0.5,
    },
    {
        id: 3,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-2-600x600.jpg',
        name : 'AC Delco 45H2130 Coil Springs',
        price : 102,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 4,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-1-600x600.png',
        name : 'Air Filter',
        price : 65,
        rate: 4.5 ,
        precise : 0.5,
    },
    {
        id: 5,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/prod_2_deposit_opt-600x600.jpg',
        name : 'Air Intake Pump',
        price : 360,
        rate: 4.25 ,
        precise : 0.5,
    },
    {
        id: 6,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-13-400x400.jpg',
        name : 'Aluminum Wheels Concave Rim',
        price : 3214,
        rate: 4.00 ,
        precise : 0.5,
    },
    {
        id: 7,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-26-600x600.jpg',
        name : 'Braking Blocks (Maintenance Kit)',
        price : 324,
        rate: 3 ,
        precise : 0.5,  
    },
    {
        id: 8,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-16.jpg',
        name : 'Brandix Brake Kit',
        price : 3021,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 9,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pro-3-600x600.jpg',
        name : 'Car Sports Seat',
        price : 897,
        rate: 1 ,
        precise : 0.5,
    },
    {
        id: 10,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-10.jpg',
        name : 'Car Vacuum Cleaner 120W',
        price : 365,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 11,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-23-600x600.jpg',
        name : 'Combo Sports Stereos fo...',
        price : 563,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 12,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/Light-5-600x600.jpg',
        name : 'DRL Bar Projector Head...',
        price : 456,
        rate: 3 ,
        precise : 0.5,
    },
    {
        id: 13,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-6-600x600.jpg',
        name : 'Dual Usb Port Mobile Phone Charging Adapter',
        price : 496,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 14,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-4-600x600.jpg',
        name : 'Engine Block',
        price : 325,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 15,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-19-600x600.jpg',
        name : 'Engine Maintenance Kit',
        price : 3641,
        rate: 1 ,
        precise : 0.5,
    },
    {
        id: 16,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-32-600x600.jpg',
        name : 'Fantastic 12-Stroke Engine With A Power of 1991 HP',
        price : 978,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 17,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-5.jpg',
        name : 'Headlight For Toyota',
        price : 635,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 18,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-21-600x600.jpg',
        name : 'Motor Oil Level 5W',
        price : 652,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 19,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/Repair-Parts-41.jpg',
        name : 'OE Replacement Engine',
        price : 563,
        rate: 4.5 ,
        precise : 0.5,
    },
    {
        id: 20,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-7.jpg',
        name : 'Portable 12V 4 Inch Car Mini Air Fan',
        price : 1354,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 21,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/e-p-6-1.jpg',
        name : 'Powerstroke Engines Turbo Air Products',
        price : 563,
        rate: 3 ,
        precise : 0.5,
    },
    {
        id: 22,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-17.jpg',
        name : 'Radial Tires 165/70R13',
        price : 365,
        rate: 3 ,
        precise : 0.5,
    },
    {
        id: 23,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/Repair-Parts.jpg',
        name : 'Replace – OE Replacement Engine',
        price : 2356,
        rate: 0 ,
        precise : 0.5,
    },
    {
        id: 24,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-25.jpg',
        name : 'Set of Four 19 Inch Spiked Tires',
        price : 205,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 25,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-27.jpg',
        name : 'Side View Mirror',
        price : 108,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 26,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-28.jpg',
        name : 'Spark Plug Kit',
        price : 36,
        rate: 0 ,
        precise : 0.5,
    },
    {
        id: 27,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-24.jpg',
        name : 'Taillights Brandix Z85',
        price : 563,
        rate: 0 ,
        precise : 0.5,
    },
    {
        id: 28,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-20.jpg',
        name : 'Twin Exhaust Pipe',
        price : 156,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 29 ,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-31.jpg',
        name : 'Two Clutch Disc',
        price : 321,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 30 ,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-22.jpg',
        name : 'Wheel Cleaner',
        price : 563,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 1,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-29-600x600.jpg',
        name : '6 Speed Gearbox',
        price : 644,
        rate: 4.25 ,
        precise : 0.5,
    },
    {
        id: 2,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-4-600x600.jpg',
        name : '600-Series Floor Mount 3-Pedal Assembly',
        price : 457,
        rate: 4.5 ,
        precise : 0.5,
    },
    {
        id: 3,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-2-600x600.jpg',
        name : 'AC Delco 45H2130 Coil Springs',
        price : 102,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 4,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-1-600x600.png',
        name : 'Air Filter',
        price : 65,
        rate: 4.5 ,
        precise : 0.5,
    },
    {
        id: 5,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/prod_2_deposit_opt-600x600.jpg',
        name : 'Air Intake Pump',
        price : 360,
        rate: 4.25 ,
        precise : 0.5,
    },
    {
        id: 6,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-13-400x400.jpg',
        name : 'Aluminum Wheels Concave Rim',
        price : 3214,
        rate: 4.00 ,
        precise : 0.5,
    },
    {
        id: 7,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-26-600x600.jpg',
        name : 'Braking Blocks (Maintenance Kit)',
        price : 324,
        rate: 3 ,
        precise : 0.5,  
    },
    {
        id: 8,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-16.jpg',
        name : 'Brandix Brake Kit',
        price : 3021,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 9,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pro-3-600x600.jpg',
        name : 'Car Sports Seat',
        price : 897,
        rate: 1 ,
        precise : 0.5,
    },
    {
        id: 10,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-10.jpg',
        name : 'Car Vacuum Cleaner 120W',
        price : 365,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 11,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-23-600x600.jpg',
        name : 'Combo Sports Stereos fo...',
        price : 563,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 12,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/Light-5-600x600.jpg',
        name : 'DRL Bar Projector Head...',
        price : 456,
        rate: 3 ,
        precise : 0.5,
    },
    {
        id: 13,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-6-600x600.jpg',
        name : 'Dual Usb Port Mobile Phone Charging Adapter',
        price : 496,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 14,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-4-600x600.jpg',
        name : 'Engine Block',
        price : 325,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 15,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-19-600x600.jpg',
        name : 'Engine Maintenance Kit',
        price : 3641,
        rate: 1 ,
        precise : 0.5,
    },
    {
        id: 16,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-32-600x600.jpg',
        name : 'Fantastic 12-Stroke Engine With A Power of 1991 HP',
        price : 978,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 17,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-5.jpg',
        name : 'Headlight For Toyota',
        price : 635,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 18,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-21-600x600.jpg',
        name : 'Motor Oil Level 5W',
        price : 652,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 19,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/Repair-Parts-41.jpg',
        name : 'OE Replacement Engine',
        price : 563,
        rate: 4.5 ,
        precise : 0.5,
    },
    {
        id: 20,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-7.jpg',
        name : 'Portable 12V 4 Inch Car Mini Air Fan',
        price : 1354,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 21,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/e-p-6-1.jpg',
        name : 'Powerstroke Engines Turbo Air Products',
        price : 563,
        rate: 3 ,
        precise : 0.5,
    },
    {
        id: 22,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-17.jpg',
        name : 'Radial Tires 165/70R13',
        price : 365,
        rate: 3 ,
        precise : 0.5,
    },
    {
        id: 23,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/Repair-Parts.jpg',
        name : 'Replace – OE Replacement Engine',
        price : 2356,
        rate: 0 ,
        precise : 0.5,
    },
    {
        id: 24,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-25.jpg',
        name : 'Set of Four 19 Inch Spiked Tires',
        price : 205,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 25,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-27.jpg',
        name : 'Side View Mirror',
        price : 108,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 26,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-28.jpg',
        name : 'Spark Plug Kit',
        price : 36,
        rate: 0 ,
        precise : 0.5,
    },
    {
        id: 27,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-24.jpg',
        name : 'Taillights Brandix Z85',
        price : 563,
        rate: 0 ,
        precise : 0.5,
    },
    {
        id: 28,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-20.jpg',
        name : 'Twin Exhaust Pipe',
        price : 156,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 29 ,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-31.jpg',
        name : 'Two Clutch Disc',
        price : 321,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 30 ,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-22.jpg',
        name : 'Wheel Cleaner',
        price : 563,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 1,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-29-600x600.jpg',
        name : '6 Speed Gearbox',
        price : 644,
        rate: 4.25 ,
        precise : 0.5,
    },
    {
        id: 2,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-4-600x600.jpg',
        name : '600-Series Floor Mount 3-Pedal Assembly',
        price : 457,
        rate: 4.5 ,
        precise : 0.5,
    },
    {
        id: 3,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-2-600x600.jpg',
        name : 'AC Delco 45H2130 Coil Springs',
        price : 102,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 4,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-1-600x600.png',
        name : 'Air Filter',
        price : 65,
        rate: 4.5 ,
        precise : 0.5,
    },
    {
        id: 5,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/prod_2_deposit_opt-600x600.jpg',
        name : 'Air Intake Pump',
        price : 360,
        rate: 4.25 ,
        precise : 0.5,
    },
    {
        id: 6,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-13-400x400.jpg',
        name : 'Aluminum Wheels Concave Rim',
        price : 3214,
        rate: 4.00 ,
        precise : 0.5,
    },
    {
        id: 7,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-26-600x600.jpg',
        name : 'Braking Blocks (Maintenance Kit)',
        price : 324,
        rate: 3 ,
        precise : 0.5,  
    },
    {
        id: 8,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-16.jpg',
        name : 'Brandix Brake Kit',
        price : 3021,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 9,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pro-3-600x600.jpg',
        name : 'Car Sports Seat',
        price : 897,
        rate: 1 ,
        precise : 0.5,
    },
    {
        id: 10,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-10.jpg',
        name : 'Car Vacuum Cleaner 120W',
        price : 365,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 11,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-23-600x600.jpg',
        name : 'Combo Sports Stereos fo...',
        price : 563,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 12,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/Light-5-600x600.jpg',
        name : 'DRL Bar Projector Head...',
        price : 456,
        rate: 3 ,
        precise : 0.5,
    },
    {
        id: 13,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-6-600x600.jpg',
        name : 'Dual Usb Port Mobile Phone Charging Adapter',
        price : 496,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 14,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-4-600x600.jpg',
        name : 'Engine Block',
        price : 325,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 15,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-19-600x600.jpg',
        name : 'Engine Maintenance Kit',
        price : 3641,
        rate: 1 ,
        precise : 0.5,
    },
    {
        id: 16,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-32-600x600.jpg',
        name : 'Fantastic 12-Stroke Engine With A Power of 1991 HP',
        price : 978,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 17,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-5.jpg',
        name : 'Headlight For Toyota',
        price : 635,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 18,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-21-600x600.jpg',
        name : 'Motor Oil Level 5W',
        price : 652,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 19,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/Repair-Parts-41.jpg',
        name : 'OE Replacement Engine',
        price : 563,
        rate: 4.5 ,
        precise : 0.5,
    },
    {
        id: 20,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-7.jpg',
        name : 'Portable 12V 4 Inch Car Mini Air Fan',
        price : 1354,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 21,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/e-p-6-1.jpg',
        name : 'Powerstroke Engines Turbo Air Products',
        price : 563,
        rate: 3 ,
        precise : 0.5,
    },
    {
        id: 22,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-17.jpg',
        name : 'Radial Tires 165/70R13',
        price : 365,
        rate: 3 ,
        precise : 0.5,
    },
    {
        id: 23,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/Repair-Parts.jpg',
        name : 'Replace – OE Replacement Engine',
        price : 2356,
        rate: 0 ,
        precise : 0.5,
    },
    {
        id: 24,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-25.jpg',
        name : 'Set of Four 19 Inch Spiked Tires',
        price : 205,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 25,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-27.jpg',
        name : 'Side View Mirror',
        price : 108,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 26,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-28.jpg',
        name : 'Spark Plug Kit',
        price : 36,
        rate: 0 ,
        precise : 0.5,
    },
    {
        id: 27,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-24.jpg',
        name : 'Taillights Brandix Z85',
        price : 563,
        rate: 0 ,
        precise : 0.5,
    },
    {
        id: 28,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-20.jpg',
        name : 'Twin Exhaust Pipe',
        price : 156,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 29 ,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-31.jpg',
        name : 'Two Clutch Disc',
        price : 321,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 30 ,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-22.jpg',
        name : 'Wheel Cleaner',
        price : 563,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 1,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-29-600x600.jpg',
        name : '6 Speed Gearbox',
        price : 644,
        rate: 4.25 ,
        precise : 0.5,
    },
    {
        id: 2,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-4-600x600.jpg',
        name : '600-Series Floor Mount 3-Pedal Assembly',
        price : 457,
        rate: 4.5 ,
        precise : 0.5,
    },
    {
        id: 3,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-2-600x600.jpg',
        name : 'AC Delco 45H2130 Coil Springs',
        price : 102,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 4,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-1-600x600.png',
        name : 'Air Filter',
        price : 65,
        rate: 4.5 ,
        precise : 0.5,
    },
    {
        id: 5,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/prod_2_deposit_opt-600x600.jpg',
        name : 'Air Intake Pump',
        price : 360,
        rate: 4.25 ,
        precise : 0.5,
    },
    {
        id: 6,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-13-400x400.jpg',
        name : 'Aluminum Wheels Concave Rim',
        price : 3214,
        rate: 4.00 ,
        precise : 0.5,
    },
    {
        id: 7,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-26-600x600.jpg',
        name : 'Braking Blocks (Maintenance Kit)',
        price : 324,
        rate: 3 ,
        precise : 0.5,  
    },
    {
        id: 8,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-16.jpg',
        name : 'Brandix Brake Kit',
        price : 3021,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 9,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pro-3-600x600.jpg',
        name : 'Car Sports Seat',
        price : 897,
        rate: 1 ,
        precise : 0.5,
    },
    {
        id: 10,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-10.jpg',
        name : 'Car Vacuum Cleaner 120W',
        price : 365,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 11,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-23-600x600.jpg',
        name : 'Combo Sports Stereos fo...',
        price : 563,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 12,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/Light-5-600x600.jpg',
        name : 'DRL Bar Projector Head...',
        price : 456,
        rate: 3 ,
        precise : 0.5,
    },
    {
        id: 13,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-6-600x600.jpg',
        name : 'Dual Usb Port Mobile Phone Charging Adapter',
        price : 496,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 14,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-4-600x600.jpg',
        name : 'Engine Block',
        price : 325,
        rate: 2 ,
        precise : 0.5,
    },
    {
        id: 15,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-19-600x600.jpg',
        name : 'Engine Maintenance Kit',
        price : 3641,
        rate: 1 ,
        precise : 0.5,
    },
    {
        id: 16,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-32-600x600.jpg',
        name : 'Fantastic 12-Stroke Engine With A Power of 1991 HP',
        price : 978,
        rate: 5 ,
        precise : 0.5,
    },
    {
        id: 17,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-5.jpg',
        name : 'Headlight For Toyota',
        price : 635,
        rate: 4 ,
        precise : 0.5,
    },
    {
        id: 18,
        pic: 'https://themebing.com/wp/sayara/wp-content/uploads/2020/04/pic-21-600x600.jpg',
        name : 'Motor Oil Level 5W',
        price : 652,
        rate: 5 ,
        precise : 0.5,
    },
];